-- Example inserts for RAG chunks.
-- Replace embedding values with real vectors generated by your embedding model.

INSERT INTO knowledge_chunks (
    source_doc_id,
    source_name,
    source_type,
    chunk_index,
    chunk_text,
    embedding,
    metadata,
    language,
    user_level,
    tags,
    token_count
) VALUES (
    'loan_faq_v1',
    'Loan product FAQ',
    'markdown',
    0,
    '初始额度不高，主要是因为平台需要控制欺诈风险。当前市场中虚假资料、恶意借款等情况较多，所以系统会先根据用户资料、还款记录和风险策略给出较保守的额度。',
    NULL,
    '{"category":"faq","user_level":"all","version":"v1","topic":"credit_limit"}'::jsonb,
    'zh-CN',
    'all',
    ARRAY['faq', 'loan', 'credit_limit'],
    96
)
ON CONFLICT (source_doc_id, chunk_index) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    chunk_text = EXCLUDED.chunk_text,
    embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata,
    language = EXCLUDED.language,
    user_level = EXCLUDED.user_level,
    tags = EXCLUDED.tags,
    token_count = EXCLUDED.token_count;

INSERT INTO knowledge_chunks (
    source_doc_id,
    source_name,
    source_type,
    chunk_index,
    chunk_text,
    embedding,
    metadata,
    language,
    user_level,
    tags,
    token_count
) VALUES (
    'loan_faq_v1',
    'Loan product FAQ',
    'markdown',
    1,
    '对于信用记录良好、能够按时还款的用户，系统会逐步提高信任等级。通常在第三次按时还款之后，额度会有明显提升，利率也可能同步降低。',
    NULL,
    '{"category":"faq","user_level":"all","version":"v1","topic":"repayment"}'::jsonb,
    'zh-CN',
    'all',
    ARRAY['faq', 'loan', 'repayment'],
    72
)
ON CONFLICT (source_doc_id, chunk_index) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    chunk_text = EXCLUDED.chunk_text,
    embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata,
    language = EXCLUDED.language,
    user_level = EXCLUDED.user_level,
    tags = EXCLUDED.tags,
    token_count = EXCLUDED.token_count;

-- Example with a real embedding vector:
-- UPDATE knowledge_chunks
-- SET embedding = '[0.012, -0.034, 0.056]'::vector
-- WHERE source_doc_id = 'loan_faq_v1' AND chunk_index = 0;
